automatepro_cam1_node:
  ros__parameters:
    camera_name: "cam1"
    camera_info_url: ""
    resolution: [640, 512]
    format: "bgr8"
    frame_id: "cam1"

    compression:
      enable: true
      format: "h264"
      bitrate: 5000    # kbps
    rtp:
      enable: false

    # Do not change the following parameters
    sensor:
      device: "/dev/video0"
      model: "SG3S-ISX031C"
      resolution: [1920, 1536]
      frame_rate: 30
      format: "UYVY"

automatepro_cam2_node:
  ros__parameters:
    camera_name: "cam2"
    camera_info_url: ""
    resolution: [640, 512]
    format: "bgr8"
    frame_id: "cam2"

    compression:
      enable: true
      format: "h264"
      bitrate: 5000    # kbps
    rtp:
      enable: false

    # Do not change the following parameters
    sensor:
      device: "/dev/video1"
      model: "SG3S-ISX031C"
      resolution: [1920, 1536]
      frame_rate: 30
      format: "UYVY"
