automatepro_imu_driver:
  ros__parameters:

    frame_id: "imu"
    i2c:
      enabled: true
      bus: "/dev/i2c-7"
      address: "0x4B"

    publish:
      magnetic_field: 
        enabled: true
        rate: 100   # max 100 Hz
      imu:
        enabled: true
        rate: 100   # max 400 Hz 
